spring:
  application:
    name: MAGE
  datasource:
      url: jdbc:mysql://localhost:3306/
      username: root
      password: TG-MAGE
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true